<a href="https://colab.research.google.com/github/lsuhpchelp/loniscworkshop2025/blob/main/day2/IntermediatePython_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Day 2: Intermediate Python (Exercises)**
### 2025 LONI Scientific Computing Bootcamp

Dr. Jianxiong "Jason" Li

jasonli3@lsu.edu

Jun 3, 2025

In [4]:
# Run this first so that you do not have to load NumPy every time
import numpy as np

<br><br>

---
## **1. Warm Up**
---

### **1) Creation:**

Create a 1-D array:

* Type is `float32`
* From `0` to no more than `30`, step length is `3`
* Do not use `np.array()` method!
* Desired output:
>```
[0. 3. 6. 9. 12. 15. 18. 21. 24. 27.]
float32
```

In [ ]:
myAry = # FIX ME
print(myAry)
print(myAry.dtype)

### **2) Reshape**

* Reshape the above 1-D array to a 2-D array with 2 rows
* Desired output:
>```
[[ 0.  3.  6.  9. 12.]
 [15. 18. 21. 24. 27.]]
 ```

In [ ]:
myAry2 = # FIX ME
print(myAry2)

### **3) Slicing**

* From the original 1D array, get every second element in the reverse order from index 5
* Desired output:

> ```
[15, 9, 3]
 ```

In [ ]:
myAry3 = # FIX ME
print(myAry3)

* From above array, pick every other element on axis 1, and keep axis 0
* Desired out
> ```
  [[ 0.  6. 12.]
  [15. 21. 27.]]
  ```

In [1]:
myAry4 = # FIX ME
print(myAry4)

SyntaxError: invalid syntax (2891490207.py, line 1)

### **4) Basic Operations**

* For above array, calculate the square of each element, then change the data type to `int`
* Desired output:
> ```
[[  0  36 144]
 [225 441 729]]
 ```

In [ ]:
myAry4 = # FIX ME
print(myAry4)

### **5) Aggregation Functions**

* For above array, sum over rows and columns of above array, respectively
* Desired output:
>```
[225 477 873]
[ 180 1395]
```

In [ ]:
row_sum = # FIX ME
print(row_sum)

col_sum = # FIX ME
print(col_sum)

### **6) Broadcast**

* Calculate Gaussian from Cartesian coordinates
$$
G(x, y) = \exp\left( -\frac{x^2 + y^2}{2\sigma^2} \right)
$$ 
Where **$$ x, y \in [-3, 3], \sigma = 1. $$**
* Gaussian is the exponent of `x^2 + y^2` (Hint: Use `np.exp()`)
* Both `x` and `y` range from `-3` to `3`, a total of linearly spaced `7` elements
* You result should be a `(7 x 7)` array, each element is the Gaussian of coordinates `(x, y)`.
* Try **NOT** to use loop even if you are attempted to!!
* Desired output:
>```
x =  [-3. -2. -1.  0.  1.  2.  3.]
y =
 [[-3.]
 [-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]]
G =
[[0.00012 0.00148 0.01111 0.04394 0.01111 0.00148 0.00012]
 [0.00148 0.01832 0.13738 0.54335 0.13738 0.01832 0.00148]
 [0.01111 0.13738 1.00000 0.36788 1.00000 0.13738 0.01111]
 [0.04394 0.54335 0.36788 1.00000 0.36788 0.54335 0.04394]
 [0.01111 0.13738 1.00000 0.36788 1.00000 0.13738 0.01111]
 [0.00148 0.01832 0.13738 0.54335 0.13738 0.01832 0.00148]
 [0.00012 0.00148 0.01111 0.04394 0.01111 0.00148 0.00012]]
 ```

In [5]:
x = # FIX ME
y = # FIX ME
sigma=1
print("x = ", x)
print("y = \n", y)

#Hint: Use np.exp() to calculate the Gaussian
G = # FIX ME
np.set_printoptions(suppress=True, precision=5) #Avoid printing in scientific format
print("G = \n", G)

SyntaxError: invalid syntax (4234285557.py, line 1)

<br><br>

---
## **2. Write Your Own ReLU Function**
---

> * The purpose of this exercise is to practice the use of advanced indexing.

Rectified Linear Unit (ReLU) is a commonly used activation function in machine learning. The definition is simple:

![P_2_ReLU.png](https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/images/P_2_ReLU.png)

Here, you are asked to write your own ReLU funcion acting on a data array:

* **Input**:
  * An array of numbers (int or float).
* **Function**:
  * Changes all negative numbers in the input array to 0.
  * Modifies the input array **in-place** (not returning a copy of the result).

**!!CAUTION!!**

* I did not say the input is 1-D array. Could be any arbitrary shape.
* Use ufunc, advanced indexing and/or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!! Don't do anything like this:
>```
for i in range(x.size):
    if x[i]<0:
      ...
```
* Hint: Feel free to use any method to achieve it. Below I provided hints to two differnt methods using what we talked about today:
  * Method 1: Keep in mind boolean array indexing is a reference.
  * Method 2: When used in arithmatic calculation, boolean value `True` is treated as `1`, and `False` as `0`.

In [ ]:
# Define your own ReLU function
def relu(x):
  # FIX ME

myAry = np.random.random([5, 5]) - 0.5
print("Input = \n", myAry)

relu(myAry)
print("\nOutput = \n", myAry)

<br><br>

---
## **3. Statistics with NumPy**
---

> * The purpose of this exercise is to practice the use of slicing, aggregation functions and advanced indexing.

### **Example 1** ###

In this example, you are monitoring the height (in cm) of 3 plants over 7 days in your lab. You need to calculate the growth of these 3 plants over 7 days. Use NumPy to analyze and simulate their growth.

**These are your tasks:**

* Create the numpy array
* Simulate a fertilizer boost, e.g, each plant height is growing by 5% per each day (multiply with 1.05 every height)
* Compute statistics like average height, max height, and total growth


In [3]:
# 1. Create a NumPy array with heights (in cm) of 3 plants over 7 days
# Use np.array() to define this 2D array (shape: 3x7)
# Hint: Use np.array with 3 sub-lists (one per plant)

# Plant A: 10, 12, 14, 15, 15.5, 16, 17
# Plant B: 8, 8.5, 9, 9.8, 10.2, 11, 12
# Plant C: 9, 9.5, 10.5, 11, 11.8, 12.5, 13

heights = # FIX ME
print("heights\n= ", heights)

SyntaxError: invalid syntax (389339653.py, line 9)

In [ ]:
# 2. Simulate a fertilizer boost: each plant grow 5% more each day
# Use a universal function (ufunc) to scale each plant height by 1.05
# Hint: Use element-wise multiplication

boosted = # FIX ME
print("boosted \n= ", boosted)

In [ ]:
# 3. Calculate the average and maximum height per plant across 7 days
# Use np.mean with appropriate axis
# Hint: axis=1 gives row-wise mean (per plant)

avg_per_plant = # FIX ME
max_per_plant = # FIX ME

# Calculate total growth over 7 days (final height - initial height)
# Hint: Access first and last column of each row

growth = # FIX ME

print("\n Average per Plant\n = ", avg_per_plant)
print("\n Maximum per Plant\n = ", max_per_plant)
print("Total growth in 7 days:", growth)

### **Example 2** ###

This is another similar example. Here, you are asked to perform some basic statistical calculation on the data array previously loaded from "data.txt". The loaded data should have 3 columns:
> ```
Index, Brain Weight, Body Weight
```

**!!CAUTION!!**

* Use aggregation functions, advanced indexing or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!!

In [ ]:
# Load data

txtfile = 'https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/data.txt'
data = np.loadtxt(txtfile,
                  skiprows=16,
                  usecols={0,1,2},
                  comments="#")
print("Loaded data:\n", data)

### **1) Calculate the average, max, and min brain weight and body weight, respectively**

Complete the below calculations.

In [ ]:
# Calculate average, max, and min brain weight
ave_brain_weight = # FIX ME
max_brain_weight = # FIX ME
min_brain_weight = # FIX ME
print("Average brain weight is:\t", ave_brain_weight)
print("Max brain weight is:\t", max_brain_weight)
print("Min brain weight is:\t", min_brain_weight)

# Calculate average, max, and min body weight
ave_body_weight = # FIX ME
max_body_weight = # FIX ME
min_body_weight = # FIX ME
print("Average brain weight is:\t", ave_body_weight)
print("Max brain weight is:\t", max_body_weight)
print("Min brain weight is:\t", min_body_weight)

### **2) Filter out bad data points**

Now, notice there is a bad point: Someone's brain is heavier than the body! That is physically impossible. Please remove any rows where the brain is heavier than the body, and redo above calculation.

Hint: Use advanced indexing.

In [ ]:
# Filter out bad data points
data_filtered = # FIX ME
print("Filtered data:\n", data_filtered)

# Calculate average, max, and min brain weight
ave_brain_weight = # FIX ME
max_brain_weight = # FIX ME
min_brain_weight = # FIX ME
print("Average brain weight is:\t", ave_brain_weight)
print("Max brain weight is:\t", max_brain_weight)
print("Min brain weight is:\t", min_brain_weight)

# Calculate average, max, and min body weight
ave_body_weight = # FIX ME
max_body_weight = # FIX ME
min_body_weight = # FIX ME
print("Average brain weight is:\t", ave_body_weight)
print("Max brain weight is:\t", max_body_weight)
print("Min brain weight is:\t", min_body_weight)

<br><br>

---
## **[BONUS] Wave Function Propagation of 1-D Harmonic Oscillator**
---

> * The purpose of this exercise it to practice various NumPy array creationg methods, ufuncs, and aggregation functions in a close-to-practical problem.
> * Don't worry if you do not work in physics! You can still finish the exercise even if you do not know the physics.

1-D harmonic oscillator is one of the most fundamental dynamic systems in both classical and quantime-mechanical physics. It describes the dynamics of a particle inside a square potential `V(x) ∝ x^2`. In classical picture, it is just a mass attached to a spring oscillating back and forth. In quantum-mechanical picture, however, is a little more complicated.

In quantum mechanics, a particle is not located in a fixed place, instead it has a **probability distribution** of where it may be found, which is defined by a **wave function**. In a quantum-mechanical picture, instead of the particle itself oscillating back and forth, it looks more like its probability distribution (a "wave packet", if you will) oscillating back and forth, but in the same way the mass does in the classical picture.

![P_4_scenario.png](https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/images/P_4_scenario.png)


Here, you are asked to write a simple code to study how the wave function of a 1-D harmonic oscillator propagates using quantum mechanical methods.

**!!CAUTION!!**

* Use aggregation functions, ufuncs or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!!

### **1) Create the initial wave function on a discrete grid**

First create a 1-D array of `x` coordinates from `[-L/2, L/2]` (`L=10.`), evenly spaced in `N=101` grid points. You will also need to find out step length `dx`.

Then create the initial wave function on the above grid, which should look like:

![P_4_psi.png](https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/images/P_4_psi.png)

The `√C` is the normalization factor.

In [ ]:
# Define parameters
N = 101       # Number of grid points
L = 10.0      # Length of the box

# Define the array x coordinates and obtrain step length dx
# Hint: You may np.linspace() to create the array and return the step length
x, dx = # FIX ME

# Calculate the initial wave function
# For simplicity, first calculate without dividing by normalization factor "√N", then do the normalization
# Hint: You may need np.exp(), np.sqrt(), sum()
psi = # FIX ME
psi /= # FIX ME

# Plot probability distribution abs(psi)**2
import matplotlib.pyplot as plt
plt.plot(x, np.abs(psi)**2, label="Wave function")
plt.legend()
plt.show()

### **2) Create the Hamiltonian matrix**

The Hamiltonian matrix is core of the dynamics in quantume mechanics. The Hamiltonian matrix is an `(N, N)` matrix (NumPy array), which can be defined this way:

![P_4_H.png](https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/images/P_4_H.png)

Basically, matrix `T` (kinetic energy) is a tridiagonal matrix, with all diagonal elements being `-2` and off-diagonal elements being `1`, then times a constant `-1/dx^2`. Matrix `V` (potential energy) is a diagonal matrix, with each element is the potential energy `V(x)=x^2/2` at the corresponding coordinate. All other unwritten elements are `0`.

In [ ]:
# Create matrix T
# Hint: You may need np.diag(), np.identity(), or np.eye(). Don't forget argument "k" sets off diagonal elements.
T = # FIX ME

# Create matrix V
# Hint: You may need np.diag()
V = # FIX ME

# Create Hamiltonian matrix H
H = T + V

# Print Hamiltonian matrix
print(H)

### **3) Build the propagator**

Now we are getting to the good stuff which (likely) only theoretical physicists know! By doing this, you can proudly tell your friends that you did some actual theoretical physics!

Based on the Hamiltonian matrix, we will now build the propagator, a matrix you actually multiple to the left of the wave function. The propagator is defined like this:

![P_4_CN.png](https://github.com/lsuhpchelp/loniscworkshop2025/raw/main/day2/images/P_4_CN.png)

Where `I` is the `(N, N)` identity matrix, `i` is the imaginary unit, and `dt` is the time step length. Here we will let time goes from `0` to `4*pi`, and a total of `Nt=20,000` steps, so that step length is short enough. Notice that there is a matrix inverse and a matrix multiplications!

> This method is called Crank-Nicholson method, the most commonly used numerical method to propagate wave function. The reason we form the propagator this way is to preserve normalization of the wave function.

In [ ]:
# Define time coordinates and return time step length dt
# Hint: You may np.linspace() to create the array and return the time step
tmin = 0
tmax = 4*np.pi
Nt = 20000
t, dt = # FIX ME
print("Time step length is:", dt)

# Create the propagator
# Hint: You may need:
#       np.linalg.inv(A)  : Matrix inverse
#       np.dot(A,B)       : Matrix multiplication
#       1j                : Imaginary unit
U = # FIX ME

# Print the propagator
print("Propagator is:\n", U)

# Look, your propagator should be close to an identity matrix

### **4) Let's see the results!**

Now let's see the results! This part is not very related to NumPy, so I will not ask you to write or understand. But if you have done correctly in previous steps, just run this part and you should see a nice animation of wave packet oscillating back and forth like a classical particle. If it is messed up, check previous steps again.

In [ ]:
#@markdown (Run me. I promise there is no harm.)

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Change psi to complex number
psi = psi.astype("complex")

# Create a figure and axes
fig, ax = plt.subplots()

# Set the x and y axis of the plot
ax.set_xlim(-L/2, L/2)
ax.set_ylim(0, 1)

# Initialize an empty line object
ax.plot(x, x**2/20, "--")
line, = ax.plot([], [])

# Define the animation update function
nframe = 100
def update(frame):

    # Generate y values based on the frame number
    global psi
    global nframe
    for index in range(int(Nt/nframe)):
      psi = np.dot(U, psi)

    # Update the line data
    line.set_data(x, np.abs(psi)**2)

    return line,

# Create the animation
animation = FuncAnimation(fig, update, frames=nframe, interval=50, blit=True)

#animation.save("P_4_result.gif")
from IPython.display import HTML
HTML(animation.to_jshtml())

If you are doing it correctly, you should get something like this:
![P_4_result.gif](https://github.com/lsuhpchelp/loniscworkshop2024/raw/main/day2/images/P_4_result.gif)

Now, congratulations! You just did some physics research!

FYI, what you just did is actually solving the most fundamental equation in quantum mechanics: **Time-Dependent Schrodinger's Equation** (**TDSE**). TDSE governs the quantum-mechanical dynamics of the microscopic particles. In actual research, physicists usually propagate TDSE like this to see how wave function evolve in time to extract useful information. And TDSE results are sometimes regarded as the **exact** results, pretty much equivalent to what you would get in experiments.

But actual research problems could be much more costly. They may need larger grid, 3-D instead of 1-D, spherical coordinates, multiple particles, different physics models, etc..